### ISSUE TITLE
How to request default logger if there is no access too "app" object?

### ISSUE THREAD

**Issue by artas728** [lwinterface/panini#51]
```
from panini.utils.logger import get_logger

log = get_logger()
```

result:

`TypeError: get_logger() missing 1 required positional argument: 'name'
`

Could we handle this case?

**Comment by danylott** [comment]
Oh, yes, good question - I can provide the default parameter for the name, such as "app", 
but in global case - you can use one of the default config handlers names to get the logger:
https://github.com/lwinterface/panini/tree/master/panini/utils#log-config
for ex: 
`get_logger("panini")`
`get_logger("inter_services_request")`

**Comment by danylott** [comment]
By the way, I got a problem - the default logger is with app.service_name, but if we don't have the name of microservice - that can be the problem, but you still could use "panini", "inter_services_request" or "app" (the most global one) logger

**Comment by danylott** [comment]
By default - the name of the get_logger will be set to "panini" (in next commit), which will be not the `app.logger` by default - but the logger with "panini" name,
But If for some reason - it is extremely important to use the default `app.logger` (the logger, with the `app.service_name` name), but you don't have the service_name there, you could use `get_app().logger` (don't forget to import from app.py) instead of `get_logger(name)`
