### ISSUE TITLE
Panini dashboard

### ISSUE THREAD

**Issue by artas728** [lwinterface/panini#83]
What do we need in order to reach good observability by default:
1)Latency
2)Response: success, timeout, another error kind
3)Response Error rate
4)Messages size
5)NATS numbers
      - uptime
      - pending_bytes
      - in_msgs
      - out_msgs
      - in_bytes
      - out_bytes
      - subscriptions
      - rate_in_msgs_per_min
      - rate_out_msgs_per_min
      - rate_in_bytes_per_min
      - rate_out_bytes_per_min
6)Logs
      
 Any thought?

**Comment by artas728** [comment]
it seems [prometheus-nats-exporter](https://github.com/nats-io/prometheus-nats-exporter) doesn't support "connz" metrics  for each metric separately

**Comment by danylott** [comment]
I think, that all these metrics are fine enough, but we need to understand, that they will cause a huge efficiency problem, which is not a big issue on dev server, but we can get incorrect data for ex. from the "latency" metric because it will be called only after other middlewares were called. Or we must make the order of calling middlewares correct (LatencyMiddleware must be the closest middleware to request, NatsTimeoutMiddleware must be the last middleware called)

**Comment by artas728** [comment]
I think LatencyMiddleware would work better as a top middleware layer in order to measure the real processing time of requests, even if there is many other middlewares before callback

**Comment by artas728** [comment]
Implemented:
1)Message rate by subject
2)Message rate by status(success/failed)
3)Message latency by subject
4)Message latency quantile

**Comment by artas728** [comment]
#102
